version: '3.7'

services:
  db:
    image: mongo
    ports:
      - 5432:5432
    volumes:
      - db:/data/db
    environment:
      POSTGRES_USER: scoutApp
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: scoutApp
volumes:
  db:
