const prefix = 'PROSPECT_';

export default {
  FETCH_USER_PLAYERS: `${prefix}FETCH_USER_PLAYERS`,
  FETCH_PLAYERS_COMPLETE: `${prefix}FETCH_PLAYERS_COMPLETE`,
  DELETE_PLAYERS: `${prefix}DELETE_PLAYERS`,
};
