const prefix = 'SETTINGS_';

export default {
  UPDATE_PREFERENCES: `${prefix}UPDATE_PREFERENCES`,
  UPDATE_PREFERENCES_COMPLETED: `${prefix}UPDATE_PREFERENCES_COMPLETED`,
  FETCH_PREFERENCES: `${prefix}FETCH_PREFERENCES`,
  FETCH_PREFERENCES_COMPLETED: `${prefix}FETCH_PREFERENCES_COMPLETED`,
};
