const prefix = 'SETTINGS_';

export default {
  UPDATE_NOTIFICATIONS_SETTINGS: `${prefix}UPDATE_NOTIFICATIONS_SETTINGS`,
  FETCH_NOTIFICATIONS_SETTINGS: `${prefix}FETCH_NOTIFICATIONS_SETTINGS`,
  FETCH_NOTIFICATIONS_SETTINGS_COMPLETED: `${prefix}FETCH_NOTIFICATIONS_SETTINGS_COMPLETED`,
};
