const prefix = 'ROUTER_SHARED_';

export default {
  GO_BACK: `${prefix}GO_BACK`,
  ACCOUNT_ENTERED: `${prefix}ACCOUNT_ENTERED`,
  NAVIGATE_TO_AUTH: `${prefix}NAVIGATE_TO_AUTH`,
  NAVIGATE_TO_MAIN: `${prefix}NAVIGATE_TO_MAIN `,
  NAVIGATE_TO_PROSPECT: `${prefix}NAVIGATE_TO_PROSPECT`,
  NAVIGATE_TO_PLAYER: `${prefix}NAVIGATE_TO_PLAYER`,
  NAVIGATE_TO_SETTINGS: `${prefix}NAVIGATE_TO_SETTINGS `,
  NAVIGATE_TO_EDIT_PROSPECT: `${prefix}NAVIGATE_TO_EDIT_PROSPECT`,
  NAVIGATE_TO_IMAGE_PICKER: `${prefix}NAVIGATE_TO_IMAGE_PICKER`,
  NAVIGATE_TO_FRIEND: `${prefix}NAVIGATE_TO_FRIEND`,
  NAVIGATE_TO_EDIT_FRIENDS: `${prefix}NAVIGATE_TO_EDIT_FRIENDS`,
  NAVIGATE_TO_INVITE_POP_UP: `${prefix}NAVIGATE_TO_INVITE_POP_UP`,
  NAVIGATE_TO_MASSAGE: `${prefix}NAVIGATE_TO_FRIEND_ACT_POP_UP`,
  NAVIGATE_TO_SEARCH: `${prefix}NAVIGATE_TO_SEARCH`,
};
